### ISSUE TITLE
minimumBy and maximumBy have serious performance issues

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-community/elm-list-extra#23]
Essentially the same as here: https://github.com/elm-lang/core/issues/485.

**Comment by jvoigtlaender** [comment]
Pull request #24, when merged, solves this.

**Comment by rehno-lindeque** [comment]
@jvoigtlaender I just invited you as a contributor on the elm-\* packages, feel free to merge tag and publish fixes like these when confident.
