### ISSUE TITLE
Add setAt

### ISSUE THREAD

**Issue by abingham** [elm-community/elm-list-extra#26]
Maybe it's for good reason, but it seems lopsided to have `getAt` without the equally useful `setAt`. Am I just missing it? 

I've cobbled together a version:

```
setAt : List a -> Int -> a -> Maybe (List a)
setAt l index value =
  let
    head = List.take index l
    tail = List.drop index l |> List.tail
  in
    case tail of
      Nothing ->
        Nothing

      Just t ->
        Just (value :: t |> List.append head)
```

though, being a relative elm newb, I'm sure there's room for improvement.

**Comment by twopoint718** [comment]
@abingham that looks like a good idea. If you want, submit it as a PR with some docs. Be sure to include it in the list of exports (like `getAt`):

https://github.com/circuithub/elm-list-extra/blob/fdeecf6c9274db5e1184de959768f0965a37459f/src/List/Extra.elm#L4

**Comment by jvoigtlaender** [comment]
There has been a PR for that meanwhile: https://github.com/elm-community/elm-list-extra/pull/27
