### ISSUE TITLE
getAt should return Nothing if given a negative index

### ISSUE THREAD

**Issue by ccapndave** [elm-community/elm-list-extra#32]
Currently it will return the head of the list.

**Comment by lukewestby** [comment]
I agree, this is strange behavior and seems to just be an artifact of using `List.drop` internally. Do you want to submit a PR?

**Comment by lukewestby** [comment]
@elm-community/packages this seems like a breaking change since it's possible someone could have written code that depends on this unusual behavior. Major version change here?

**Comment by jvoigtlaender** [comment]
I agree, both with the change and with making this a major version change.

**Comment by lukewestby** [comment]
@ccapndave can you also change the documentation to say `if the index is out of range` instead of `if the list is not long enough`, to mirror the documentation for `Array.get`?

**Comment by ccapndave** [comment]
Sure :)

**Comment by mgold** [comment]
I'm pretty sure `elm-package` won't let you release changes as more breaking than they're detected to be, so this will need to be bundled with a type-level breaking change.

**Comment by jvoigtlaender** [comment]
Indeed, https://github.com/elm-lang/elm-package/issues/165.

Though maybe the next Elm version will have fixed that?

**Comment by jvoigtlaender** [comment]
But actually, no problem in the specific case here. I removed a function from this package two days ago (https://github.com/elm-community/elm-list-extra/pull/33), so there will already be a major version bump for the next release in any case.

**Comment by mgold** [comment]
That sounds fine then.
