### ISSUE TITLE
Drop elm- from package name

### ISSUE THREAD

**Issue by abadi199** [elm-community/elm-list-extra#43]
As per elm-community/Manifesto#27, and in particular this discussion: elm-community/Manifesto#27 (comment).

**Comment by abadi199** [comment]
I'm gonna need help from "owners" (@rgrempel, @jvoigtlaender, @mgold, @Apanatshka) to create a new repo called `list-extra` and add me as collaborator to that repo.

**Comment by jvoigtlaender** [comment]
Done: https://github.com/elm-community/list-extra

**Comment by abadi199** [comment]
New package has been published here http://package.elm-lang.org/packages/elm-community/list-extra/1.0.0/
